
const tractos = "IRAPUATO TRACTOS GUZMAN";
const cajas = "GUZMAN IRAPUATO CAJAS";
const dobles_tractos = "DEV GUZMAN TRACTOS DOBLES";
const dobles_cajas = "GUZMAN CAJAS DOBLES";

// 1 ORIGEN
// 1STATUSDASHBOARD: [CARGADO, VACIO, ESPERA DESCARGA y ESPERA DE CARGA].
// 2 DESTINO